language: haskell
ghc:
    - 7.6
    - 7.8
    - 7.10

env:
    - CUDA=7.0-28
    - CUDA=6.5-14
#    - CUDA=6.0-37

before_script:
    - export GHCVER=$(ghc --numeric-version)
    - | # GHC-7.8 and later require a newer version of happy and alex
        if [ $(bc -l <<< "${GHCVER%.*} >= 7.8") -eq 1 ]; then
            cabal install happy
            cabal install alex
        fi
    - cabal install c2hs

    - echo "Installing CUDA library"
    - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_${CUDA}_amd64.deb
    - sudo dpkg -i cuda-repo-ubuntu1204_${CUDA}_amd64.deb
    - sudo apt-get update -qq
    - sudo apt-get install -y cuda
    - export CUDA_HOME=/usr/local/cuda-${CUDA%%-*}
    - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64
    - export PATH=${CUDA_HOME}/bin:${PATH}

script:
    - cabal install

after_script:
    - nvidia-device-query

